# Generated by Django 5.0.1 on 2024-02-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("implementation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="recipe_image",
            field=models.ImageField(blank=True, null=True, upload_to="images_rec/"),
        ),
    ]
